name: Build for Play Store

on:
  # Enable manual run
  workflow_dispatch:
  push:
    tags:
      - '**'

jobs:
  build-aab:
    name: Build AAB for the Play Store
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup cache
        uses: actions/cache/restore@v4
        with:
          path: |
            .dart_tool/
            build/
            linux/flutter/ephemeral/
            macos/Flutter/ephemeral/
            windows/flutter/ephemeral/
            .flutter-plugins-dependencies
            pubspec.lock
          key: ${{ runner.OS }}-ricochlime-ubuntu-${{ hashFiles('**/pubspec.lock') }}-${{ hashFiles('**/*.dart') }}
          restore-keys: |
            ${{ runner.OS }}-ricochlime-ubuntu-

      - name: Remove dev dependencies
        run: ./patches/remove_dev_dependencies.sh

      - name: Setup keystore
        run: |
          echo "${{ secrets.SIGNING_KEY }}" | base64 -d > android/android.keystore
          echo "storePassword=${{ secrets.KEY_STORE_PASSWORD }}" > android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.ALIAS }}" >> android/key.properties
          echo "storeFile=../android.keystore" >> android/key.properties

      - name: Setup Flutter
        uses: adil192/setup-flutter-submodule@v1
        with:
          flutter-path: submodules/flutter

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'microsoft'
          java-version: '21'

      - run: flutter pub get

      - name: Build aab
        run: |
          flutter build appbundle

      - name: Rename aab
        run: |
          mkdir -p output
          mv build/app/outputs/bundle/release/app-release.aab output/Ricochlime.aab

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Ricochlime-Android-PlayStore
          path: output/Ricochlime.aab

  upload-to-play-store:
    name: Upload to Play Store
    runs-on: ubuntu-latest
    needs: build-aab
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: Ricochlime-Android-PlayStore
          path: output

      - name: Prepare whatsnew directory from metadata/*/changelogs
        working-directory: ${{ github.workspace }}
        run: |
          # display changelogs for debugging
          find metadata -name '*.txt'

          mkdir -p whatsnew

          # get current version code from pubspec.yaml (the part after the +)
          VERSION_CODE=$(grep -oP '(?<=version: ).*' pubspec.yaml | grep -oP '(?<=\+).*$')

          # copy changelogs of each language to whatsnew
          for dir in metadata/*/changelogs; do
              # get language code from directory name
              # e.g. metadata/en-US/changelogs -> en-US
              lang=${dir#metadata/}
              lang=${lang%/changelogs}

              # copy changelog file to whatsnew
              cp "$dir/$VERSION_CODE.txt" "whatsnew/whatsnew-${lang}"
          done

      - name: Upload to Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.PLAY_STORE_JSON }}
          packageName: com.adilhanney.ricochlime
          releaseFiles: output/Ricochlime.aab
          track: production
          status: completed
          whatsNewDirectory: whatsnew
